//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebThuVienV2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ChiTietHoaDon
    {
        public int MaHD { get; set; }
        public string MaSach { get; set; }
        public Nullable<short> SoLuong { get; set; }
        public Nullable<float> DonGiaBan { get; set; }
        public Nullable<float> GiamGia { get; set; }
    
        public virtual Sach Sach { get; set; }
        public virtual HoaDon HoaDon { get; set; }
    }
}
